### ISSUE TITLE
The application does not find a service that was started before the app. 

### ISSUE THREAD

**Issue by creadicted** [FlorianBauer/sila-orchestrator#2]
If I have a SiLA server running and start the application, the server will not be detected by the scan method. 
If I close the server, restart and scan again the application will pick it up.

**Comment by FlorianBauer** [comment]
Thanks for reporting. However some information about your system and logs would be appreciated.

Logs are usually placed at `/home/$USER/.sila/sila_features.log` on Linux and `C:\Users\$USER\.sila sila_features.log` under Windows. More detailed logs can be retrieved by starting the *.jar package directly (with `java -jar "path/to/sila-orchestrator.jar"` in the Linux bash or Windows PowerShell) and by copying the  output out of the console window directly (`Ctrl+C` on Win or `Ctrl+Shift+C` on Linux).

To obviate that the issue is really caused by the sila-orchestrator itself and not the mentioned server, a test with a [e.g. different SiLA server](https://github.com/FlorianBauer/task-launcher) would be also advised.

Also check your Firewall settings and ensure the mentioned server is running properly (IPs and Ports are not double used etc.). It is also common that a fresh started server may take a while (~30 sec) before an network scan is able to detect its services.

**Comment by QTimort** [comment]
This PR https://github.com/FlorianBauer/sila-orchestrator/pull/3 might solve your issue, the network scan is not done correctly, the application will scan the network and check the state of the server manager, but server don't necessarily respond right away. Server addition should be done through the Server Listener available in the Server Manager.

**Comment by creadicted** [comment]
I will test it with the next version. I scaned the log but there was nothing out of the ordinary.

**Comment by FlorianBauer** [comment]
Thanks for checking. The scan routine currently got an big overhaul with the PR #3, which should solve this issue. The changes can be obtained by checking out the current master.
